global_map:
  ros__parameters:
      pcd :   "src/bringup/pcd/rmuc_2025.pcd" #先验点云的路径
      map_frame  :      "map"   #地图坐标系
      resolution :      0.1     #栅格分辨率（米/格
      map_size_x :      10.0    #地图X方向尺寸（米)
      map_size_y :      10.0    #地图y方向尺寸（米)
      obstacle_height_threshold: 0.1     #障碍物高度阈值
      ground_height_threshold: 0.05  #地面高度阈值（用于区分地面/噪声）
      voxel_leaf_size: 0.05       #体素滤波分辨率（降采样）
      max_point_height: 2.0     #最大有效高度（过滤异常点)
    
local_map:
  ros__parameters:
      map_frame  :      "map"   #地图坐标系
      resolution :      0.1     #栅格分辨率（米/格
      map_size_x :      10.0    #地图X方向尺寸（米)
      map_size_y :      10.0    #地图y方向尺寸（米)
      obstacle_height_threshold: 0.1     #障碍物高度阈值
      ground_height_threshold: 0.05  #地面高度阈值（用于区分地面/噪声）
      voxel_leaf_size: 0.05       #体素滤波分辨率（降采样）
      max_point_height: 2.0     #最大有效高度（过滤异常点)
    